"""enable email

Revision ID: 09910ca884fb
Revises: ea6aa7f7e753
Create Date: 2026-06-11 06:17:40.275579

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = "09910ca884fb"
down_revision = "ea6aa7f7e753"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job",
        sa.Column(
            "send_email_notification",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "send_email_notification")
    # ### end Alembic commands ###
