"""init

Revision ID: 226ff31bd3ad
Revises: 
Create Date: 2026-06-06 15:51:01.772618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '226ff31bd3ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('otp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('job',
    sa.Column('status', sa.Enum('open', 'purchased', 'en_route', 'completed', name='status'), nullable=False),
    sa.Column('service_type', sa.Enum('towing_transport', 'jump_start', 'tyre_change', 'winch_recovery', 'fuel_delivery', 'ev_recovery', 'accident_recovery', 'others', name='servicetype'), nullable=False),
    sa.Column('urgency', sa.Enum('immediate', 'scheduled', name='urgency'), nullable=False),
    sa.Column('lead_price', sa.Float(), nullable=False),
    sa.Column('estimated_payout', sa.Float(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=False),
    sa.Column('vehicle_class', sa.Enum('car', 'van', 'motorcycle', 'hgv_truck', 'ev', 'others', name='vehicleclass'), nullable=False),
    sa.Column('vehicle_make_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vehicle_reg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_drivable', sa.Boolean(), nullable=False),
    sa.Column('pickup_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup_area', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dropoff_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
