"""add lead

Revision ID: 8fa98549924f
Revises: 226ff31bd3ad
Create Date: 2026-06-08 22:27:58.388099

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8fa98549924f"
down_revision = "226ff31bd3ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    leadstatus = sa.Enum("open", "partial", "closed", name="leadstatus")
    leadstatus.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "leadpurchase",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purchased_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "buyer_id", name="uq_job_buyer"),
    )
    op.create_index(
        op.f("ix_leadpurchase_job_id"), "leadpurchase", ["job_id"], unique=False
    )
    op.add_column(
        "job",
        sa.Column(
            "lead_status",
            sa.Enum("open", "partial", "closed", name="leadstatus"),
            server_default="open",
            nullable=False,
        ),
    )
    op.add_column(
        "job", sa.Column("max_buyers", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "job", sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("job", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job",
        sa.Column(
            "status",
            postgresql.ENUM("open", "purchased", "en_route", "completed", name="status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("job", "closed_at")
    op.drop_column("job", "max_buyers")
    op.drop_column("job", "lead_status")
    op.drop_index(op.f("ix_leadpurchase_job_id"), table_name="leadpurchase")
    op.drop_table("leadpurchase")
    sa.Enum(name="leadstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
