"""customer fields

Revision ID: ea6aa7f7e753
Revises: cdac05c5697d
Create Date: 2026-06-11 05:27:34.539109

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea6aa7f7e753'
down_revision = 'cdac05c5697d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'customer_phone')
    op.drop_column('job', 'customer_email')
    op.drop_column('job', 'customer_name')
    # ### end Alembic commands ###
